server:
  port: 8080
  servlet:
    context-path: /community #项目名、上下文路径

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  # email
  mail:
    host: smtp.qq.com #smtp.sina.com
    #port: 465
    username: 1533183133@qq.com #nowcoder@sina.com #1533183133@qq.com
    password: cflnvstzyldjgcch #nowcoder123 #
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  # redis
  redis:
    database: 11
    host: 192.168.233.101 #localhost
    port: 6379

  # kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true #是否自动提交
      auto-commit-interval: 3000

  # elasticsearch
  data:
    elasticsearch:
      cluster-name: my-application # 同配置文件yml中的集群名字
      cluster-nodes: localhost:9300

  # TaskExecutionProperties
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    # TaskSchedulingProperties
    scheduling:
      pool:
        size: 5

  # QuartzProperties
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

mybatis:
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 自动生成 id
    use-generated-keys: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.nowcoder.community.entity

# 日志级别
logging:
  level:
    com.nowcoder.community: debug

# community
community:
  path:
    domain: http://localhost:8080
    upload: F:/work_community/upload